// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdbyKRmpwQG5O2dxxRYQcAJRyaMZqRqpw',
    appId: '1:743378862760:web:c60998521feea4067cf89d',
    messagingSenderId: '743378862760',
    projectId: 'social-app-91542',
    authDomain: 'social-app-91542.firebaseapp.com',
    storageBucket: 'social-app-91542.appspot.com',
    measurementId: 'G-LQV49X0H02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4PycX0xDgsU5ENusyMIMEdSRLeCT2mEE',
    appId: '1:743378862760:android:a9921d2cde16fd3b7cf89d',
    messagingSenderId: '743378862760',
    projectId: 'social-app-91542',
    storageBucket: 'social-app-91542.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuMdfQ1RUZoxPBvZbLls6H5IcU_MlpTpE',
    appId: '1:743378862760:ios:fe435639043be1527cf89d',
    messagingSenderId: '743378862760',
    projectId: 'social-app-91542',
    storageBucket: 'social-app-91542.appspot.com',
    iosClientId: '743378862760-8fag38ilivk87n32hqorcceqgd3q089b.apps.googleusercontent.com',
    iosBundleId: 'com.social.app.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuMdfQ1RUZoxPBvZbLls6H5IcU_MlpTpE',
    appId: '1:743378862760:ios:fe435639043be1527cf89d',
    messagingSenderId: '743378862760',
    projectId: 'social-app-91542',
    storageBucket: 'social-app-91542.appspot.com',
    iosClientId: '743378862760-8fag38ilivk87n32hqorcceqgd3q089b.apps.googleusercontent.com',
    iosBundleId: 'com.social.app.socialApp',
  );
}
